version: '3.8'
services:
  aniworld:
    container_name: aniworld-downloader
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./downloads:/app/downloads
      - ./movies:/app/movies
      - ./data:/app/data
    stdin_open: true
    tty: true
    restart: unless-stopped