name: Build with Nuitka

on:
  # push:
  #   branches:
  #     - next
  # pull_request:
  #   branches:
  #     - next
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka imageio
          pip install .

      - name: Build executable with Nuitka
        run: |
            python -m nuitka --onefile --assume-yes-for-downloads --include-package=aniworld --output-filename=aniworld.exe `
            --company-name="Phoenixthrush UwU" `
            --product-name="AniWorld Downloader" `
            --file-version=$(python -c "import toml; print(toml.load(open('pyproject.toml'))['project']['version'])") `
            --product-version=$(python -c "import toml; print(toml.load(open('pyproject.toml'))['project']['version'])") `
            --file-description="AniWorld Downloader is a command-line tool built to download and stream anime content from aniworld.to" `
            --copyright="Copyright (c) 2024-${{ github.event.date | date('yyyy') }} Phoenixthrush UwU" `
            --windows-icon-from-ico=src/aniworld/icon.png `
            src/aniworld/entry.py

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: aniworld
          path: aniworld.exe
