name: Build with Nuitka

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-13, macos-13-arm64]
        include:
          - os: windows-latest
            ext: .exe
          - os: ubuntu-latest
            ext: ""
          - os: macos-13
            ext: ""
          - os: macos-13-arm64
            ext: ""

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install toml imageio nuitka
          pip install .

      - name: Build executable with Nuitka
        run: |
          python -m nuitka --onefile --assume-yes-for-downloads --include-package=aniworld \
          --output-filename=aniworld${{ matrix.ext }} \
          --company-name="Phoenixthrush UwU" \
          --product-name="AniWorld Downloader" \
          --file-version=$(python -c "import toml; print(toml.load(open('pyproject.toml'))['project']['version'])") \
          --product-version=$(python -c "import toml; print(toml.load(open('pyproject.toml'))['project']['version'])") \
          --file-description="AniWorld Downloader is a command-line tool built to download and stream anime content from aniworld.to" \
          --copyright="Copyright (c) 2024-$(python -c 'import datetime; print(datetime.datetime.now().year)') Phoenixthrush UwU" \
          ${{ matrix.os == 'windows-latest' && '--windows-icon-from-ico=src/aniworld/icon.webp' || '' }} \
          src/aniworld/entry.py

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: aniworld-${{ matrix.os }}
          path: aniworld${{ matrix.ext }}
