name: Lint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - run: pip install . pylint

      - uses: astral-sh/ruff-action@v3
        with:
          src: "./src/aniworld"

      - run: pylint src/aniworld --disable=broad-exception-caught,missing-module-docstring || true
